[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.26"
optimizer = true
optimizer_runs = 200
via_ir = false
verbosity = 3

[rpc_endpoints]
default = "${NETWORK_RPC_URL}"

[etherscan]
default = { key = "${VERIFIER_API_KEY}", url = "${VERIFIER_URL}" }

[fuzz]
runs = 256

[invariant]
runs = 256
fail_on_revert = false